"""
ENR Top 400 Contractors — Master List
Source: ENR 2025 Top 400 Contractors (via Chubb Surety reprint)

Each entry: (rank, company_name, hq_city, state_code)
"""

ENR_TOP_400 = [
    (1, "Turner Construction Co.", "New York", "NY"),
    (2, "Bechtel", "Reston", "VA"),
    (3, "Kiewit Corp.", "Omaha", "NE"),
    (4, "The Whiting-Turner Contracting Co.", "Baltimore", "MD"),
    (5, "MasTec Inc.", "Coral Gables", "FL"),
    (6, "STO Building Group", "New York", "NY"),
    (7, "Fluor", "Irving", "TX"),
    (8, "DPR Construction", "Redwood City", "CA"),
    (9, "McDermott International", "Houston", "TX"),
    (10, "HITT Contracting", "Falls Church", "VA"),
    (11, "PCL Construction Enterprises Inc.", "Denver", "CO"),
    (12, "Skanska USA", "New York", "NY"),
    (13, "Hensel Phelps", "Greeley", "CO"),
    (14, "AECOM", "Dallas", "TX"),
    (15, "Holder Construction", "Atlanta", "GA"),
    (16, "The Walsh Group", "Chicago", "IL"),
    (17, "Gilbane Building Co.", "Providence", "RI"),
    (18, "JE Dunn Construction Co.", "Kansas City", "MO"),
    (19, "Clark Group", "McLean", "VA"),
    (20, "McCarthy Holdings Inc.", "St. Louis", "MO"),
    (21, "Clayco", "Chicago", "IL"),
    (22, "Mortenson", "Minneapolis", "MN"),
    (23, "Brasfield & Gorrie", "Birmingham", "AL"),
    (24, "Walbridge", "Detroit", "MI"),
    (25, "Zachry Group", "San Antonio", "TX"),
    (26, "Hoffman Construction", "Lake Oswego", "OR"),
    (27, "The Yates Cos. Inc.", "Philadelphia", "MS"),
    (28, "Suffolk Construction Co. Inc.", "Boston", "MA"),
    (29, "ARCO Construction Cos.", "St. Louis", "MO"),
    (30, "Swinerton Inc.", "Concord", "CA"),
    (31, "Austin Industries", "Dallas", "TX"),
    (32, "Balfour Beatty US", "Dallas", "TX"),
    (33, "Tutor Perini Corp.", "Sylmar", "CA"),
    (34, "Alberici-Flintco", "St. Louis", "MO"),
    (35, "Barton Malow Holdings LLC", "Southfield", "MI"),
    (37, "Dragados", "New York", "NY"),
    (38, "Michels", "Brownsville", "WI"),
    (39, "Granite Construction", "Watsonville", "CA"),
    (40, "Consigli Building Group Inc.", "Milford", "MA"),
    (41, "Moss", "Fort Lauderdale", "FL"),
    (42, "Burns & McDonnell", "Kansas City", "MO"),
    (43, "Ryan Cos. US Inc.", "Minneapolis", "MN"),
    (44, "Turner Industries Group LLC", "Baton Rouge", "LA"),
    (45, "Black & Veatch", "Overland Park", "KS"),
    (46, "Sundt Construction Inc.", "Tempe", "AZ"),
    (48, "Big-D Construction", "Salt Lake City", "UT"),
    (49, "The Kokosing Group of Cos.", "Westerville", "OH"),
    (50, "Crossland Construction Co. Inc.", "Columbus", "KS"),
    (51, "Flatiron Construction Corp.", "Broomfield", "CO"),
    (52, "Robins & Morton", "Birmingham", "AL"),
    (53, "Exyte Americas Holding Inc.", "Richardson", "TX"),
    (54, "F.A. Wilhelm Construction Co. Inc.", "Indianapolis", "IN"),
    (55, "Colas Inc.", "Morristown", "NJ"),
    (56, "Evans General Contractors", "Alpharetta", "GA"),
    (57, "Fortis Construction", "Portland", "OR"),
    (58, "Clune Construction", "Chicago", "IL"),
    (59, "Haskell", "Jacksonville", "FL"),
    (60, "Ferrovial Construction", "Austin", "TX"),
    (61, "Shawmut Design and Construction", "Boston", "MA"),
    (62, "Core Construction Group", "Frisco", "TX"),
    (63, "Ames Construction Inc.", "Burnsville", "MN"),
    (64, "Garney Holding Co.", "North Kansas City", "MO"),
    (65, "Day & Zimmermann", "Philadelphia", "PA"),
    (67, "J.T. Magen & Co. Inc.", "New York", "NY"),
    (68, "Construction Partners Inc.", "Dothan", "AL"),
    (69, "E. E. Reed Construction", "Sugar Land", "TX"),
    (70, "Okland Construction", "Salt Lake City", "UT"),
    (71, "Manhattan Construction Group", "Tulsa", "OK"),
    (72, "Harvey Cleary", "Houston", "TX"),
    (73, "Aristeo Construction Co.", "Livonia", "MI"),
    (74, "Miron Construction Co. Inc.", "Neenah", "WI"),
    (75, "The Christman Co.", "Lansing", "MI"),
    (76, "The Rudolph Libbe Group", "Walbridge", "OH"),
    (77, "Pepper Construction", "Chicago", "IL"),
    (78, "The Weitz Co.", "Des Moines", "IA"),
    (79, "Messer Construction Co.", "Cincinnati", "OH"),
    (80, "Alston Construction Co. Inc.", "Atlanta", "GA"),
    (81, "BL Harbert International", "Birmingham", "AL"),
    (82, "Choate Construction Co.", "Atlanta", "GA"),
    (83, "The Conlan Company", "Marietta", "GA"),
    (84, "Nabholz Construction Corp.", "Conway", "AR"),
    (85, "DEPCOM Power", "Scottsdale", "AZ"),
    (87, "Brinkmann Constructors", "Chesterfield", "MO"),
    (88, "PJ Dick - Trumbull - Lindy Group", "Pittsburgh", "PA"),
    (89, "Coastal Construction Group", "Miami", "FL"),
    (90, "Ferreira Construction Co. Inc.", "Branchburg", "NJ"),
    (91, "Hoar Construction", "Birmingham", "AL"),
    (92, "Power Construction Co. LLC", "Chicago", "IL"),
    (93, "Lane Industries Inc.", "Charlotte", "NC"),
    (94, "The Cianbro Cos.", "Pittsfield", "ME"),
    (95, "The Boldt Co.", "Appleton", "WI"),
    (96, "Adolfson & Peterson Construction", "Bloomington", "MN"),
    (97, "Caddell Construction Co. LLC", "Montgomery", "AL"),
    (98, "Hunter Roberts Construction Group LLC", "New York", "NY"),
    (99, "Samet Corp.", "Greensboro", "NC"),
    (100, "Hathaway Dinwiddie Construction Co.", "San Francisco", "CA"),
    (101, "OHLA USA Inc.", "East Elmhurst", "NY"),
    (102, "The Penta Building Group", "Las Vegas", "NV"),
    (103, "JRM Construction Management", "New York", "NY"),
    (104, "FCL Builders", "Itasca", "IL"),
    (105, "BNBuilders", "Seattle", "WA"),
    (106, "Devcon Construction Inc.", "Milpitas", "CA"),
    (107, "W.E. O'Neil Construction Co.", "Chicago", "IL"),
    (108, "Bartlett Cocke General Contractors LLC", "San Antonio", "TX"),
    (109, "ESS Cos.", "Columbia", "MO"),
    (110, "Vinci Construction USA", "Winter Park", "FL"),
    (111, "Traylor Construction Group Inc.", "Evansville", "IN"),
    (112, "Herzog Enterprises Inc.", "St. Joseph", "MO"),
    (113, "Joeris General Contractors", "San Antonio", "TX"),
    (114, "Hawaiian Dredging Construction Co. Inc.", "Honolulu", "HI"),
    (115, "Commercial Contracting Corp.", "Auburn Hills", "MI"),
    (116, "Wharton-Smith Inc.", "Sanford", "FL"),
    (117, "Rogers-O'Brien Construction", "Dallas", "TX"),
    (118, "McGough", "St. Paul", "MN"),
    (119, "Teichert Construction", "Sacramento", "CA"),
    (120, "Rycon Construction", "Pittsburgh", "PA"),
    (121, "Summit Contracting Group Inc.", "Jacksonville", "FL"),
    (122, "Webcor", "San Francisco", "CA"),
    (123, "Barnard Construction Co. Inc.", "Bozeman", "MT"),
    (124, "James G. Davis Construction Corp.", "Rockville", "MD"),
    (125, "ASRC Industrial", "Tempe", "AZ"),
    (126, "Build Group Inc.", "San Francisco", "CA"),
    (127, "Jacobsen Construction Co. Inc.", "Salt Lake City", "UT"),
    (128, "LeChase Construction Services LLC", "Rochester", "NY"),
    (129, "KPRS Construction Services Inc.", "Brea", "CA"),
    (130, "RailWorks", "New York", "NY"),
    (131, "The Beck Group", "Dallas", "TX"),
    (132, "J.H. Findorff & Son Inc.", "Madison", "WI"),
    (133, "Pogue Construction", "McKinney", "TX"),
    (134, "Anderson Columbia Co. Inc.", "Lake City", "FL"),
    (135, "The McShane Cos.", "Rosemont", "IL"),
    (136, "Dennis Group", "Springfield", "MA"),
    (137, "S&B", "Houston", "TX"),
    (138, "Phillips Infrastructure Inc.", "Knoxville", "TN"),
    (139, "F.H. Paschen", "Chicago", "IL"),
    (140, "Satterfield & Pontikes Construction Inc.", "Houston", "TX"),
    (141, "James R. Vannoy & Sons Construction Co. Inc.", "Jefferson", "NC"),
    (142, "Goodfellow Bros.", "Wenatchee", "WA"),
    (143, "ECC", "Burlingame", "CA"),
    (144, "Cajun Industries Holdings LLC", "Baton Rouge", "LA"),
    (145, "Graham Construction", "Omaha", "NE"),
    (146, "Engineered Structures Inc. (ESI)", "Meridian", "ID"),
    (147, "SpawGlass Holding", "Selma", "TX"),
    (148, "Clancy & Theys Construction Co.", "Raleigh", "NC"),
    (149, "Lease Crutcher Lewis", "Seattle", "WA"),
    (150, "Carroll Daniel Construction Co.", "Gainesville", "GA"),
    (151, "IPS-Integrated Project Services LLC", "Blue Bell", "PA"),
    (152, "Catamount Constructors Inc.", "Lakewood", "CO"),
    (153, "Jingoli - DCO", "Lawrenceville", "NJ"),
    (154, "Hanover Co.", "Houston", "TX"),
    (155, "Nan Inc.", "Honolulu", "HI"),
    (156, "Sletten Cos.", "Great Falls", "MT"),
    (157, "J.P. Cullen & Sons Inc.", "Janesville", "WI"),
    (158, "Saulsbury Industries Inc.", "Odessa", "TX"),
    (159, "Kraus-Anderson", "Minneapolis", "MN"),
    (160, "Las Vegas Paving Corp.", "Las Vegas", "NV"),
    (161, "C.W. Driver Cos.", "Pasadena", "CA"),
    (162, "Lemoine", "Lafayette", "LA"),
    (163, "APTIM", "Baton Rouge", "LA"),
    (164, "Orion Group Holdings Inc.", "Houston", "TX"),
    (165, "Williams Brothers Construction", "Houston", "TX"),
    (167, "Branch Group", "Roanoke", "VA"),
    (168, "Lee Lewis Construction Inc.", "Lubbock", "TX"),
    (169, "McCownGordon Construction", "Kansas City", "MO"),
    (170, "Great Lakes Dredge & Dock Co.", "Houston", "TX"),
    (171, "Weis Builders Inc.", "Minneapolis", "MN"),
    (172, "MWH Constructors Inc.", "Broomfield", "CO"),
    (173, "Rodgers Builders Inc.", "Charlotte", "NC"),
    (174, "Willmeng Construction Inc.", "Phoenix", "AZ"),
    (175, "Elford Inc.", "Columbus", "OH"),
    (176, "Iovino Enterprises", "Great Neck", "NY"),
    (177, "Paric Holdings", "St. Louis", "MO"),
    (178, "Level 10 Construction", "Sunnyvale", "CA"),
    (179, "Clark Construction Co.", "Lansing", "MI"),
    (180, "W. M. Jordan Co.", "Newport News", "VA"),
    (181, "Barnhill Contracting Co.", "Rocky Mount", "NC"),
    (182, "Granger Construction Co.", "Lansing", "MI"),
    (183, "Matrix Service Co.", "Tulsa", "OK"),
    (184, "CR Meyer", "Oshkosh", "WI"),
    (187, "Stellar", "Jacksonville", "FL"),
    (188, "Truebeck Construction", "San Mateo", "CA"),
    (189, "Graycor Inc.", "Oakbrook Terrace", "IL"),
    (191, "Grunley Construction Co. Inc.", "Rockville", "MD"),
    (192, "Superior Construction Holding Co. Inc.", "Jacksonville", "FL"),
    (193, "Skyline Construction", "San Francisco", "CA"),
    (194, "FCI Constructors Inc.", "Grand Junction", "CO"),
    (195, "Primus", "Woodstock", "GA"),
    (196, "Bulley & Andrews", "Chicago", "IL"),
    (197, "Electrical Consultants Inc.", "Billings", "MT"),
    (198, "Torcon Inc.", "Red Bank", "NJ"),
    (199, "Urban Atelier Group", "New York", "NY"),
    (200, "Kaufman Lynn Construction", "Delray Beach", "FL"),
    (201, "Bernards", "San Fernando", "CA"),
    (202, "Peinado Construction", "Frisco", "TX"),
    (203, "Mycon General Contractors Inc.", "Dallas", "TX"),
    (204, "Landmark Construction LLC", "Athens", "GA"),
    (205, "Harkins Builders Inc.", "Columbia", "MD"),
    (206, "Kast Construction", "West Palm Beach", "FL"),
    (207, "C D Smith Construction", "Fond du Lac", "WI"),
    (209, "Rand Construction Corp.", "Alexandria", "VA"),
    (210, "BHI", "Vernal", "UT"),
    (211, "Pike Construction Services", "Rochester", "NY"),
    (212, "Dick Anderson Construction", "Helena", "MT"),
    (213, "Zachry Construction Corp.", "San Antonio", "TX"),
    (214, "H&M Co. Inc.", "Jackson", "TN"),
    (216, "Staker Parson Materials & Construction", "Ogden", "UT"),
    (217, "DeAngelis Diamond", "Naples", "FL"),
    (218, "Rockford Construction Co.", "Grand Rapids", "MI"),
    (219, "Parkway C&A", "Lewisville", "TX"),
    (220, "DiMeo Construction Co.", "Johnston", "RI"),
    (221, "O&G Industries Inc.", "Torrington", "CT"),
    (222, "The Middlesex Corp.", "Littleton", "MA"),
    (223, "Sellen Construction Co. Inc.", "Seattle", "WA"),
    (224, "D.F. Chase Inc.", "Nashville", "TN"),
    (225, "The Korte Co.", "Highland", "IL"),
    (226, "Independence Construction", "Brecksville", "OH"),
    (227, "S&B USA", "Pittsburgh", "PA"),
    (228, "Skender", "Chicago", "IL"),
    (229, "Cahill Contractors", "San Francisco", "CA"),
    (230, "Vecellio Group Inc.", "Palm Beach", "FL"),
    (231, "Batson-Cook Construction", "Atlanta", "GA"),
    (232, "Dellbrook | JKS", "Quincy", "MA"),
    (233, "Saunders Construction Inc.", "Englewood", "CO"),
    (234, "Juneau Construction Co.", "Atlanta", "GA"),
    (236, "New South Construction Co.", "Atlanta", "GA"),
    (237, "Manson Construction Co.", "Seattle", "WA"),
    (238, "Leopardo Construction", "Hoffman Estates", "IL"),
    (239, "Roncelli Inc.", "Sterling Heights", "MI"),
    (240, "Q&D Construction", "Sparks", "NV"),
    (241, "Crowder Constructors Inc.", "Charlotte", "NC"),
    (242, "Klinger Cos. LLC", "Sioux City", "IA"),
    (243, "Shimmick", "Irvine", "CA"),
    (244, "Columbia", "North Reading", "MA"),
    (245, "Danis", "Miamisburg", "OH"),
    (246, "Stacy and Witbeck Inc.", "Alameda", "CA"),
    (248, "Oltmans Construction Co.", "Whittier", "CA"),
    (249, "M. B. Kahn Construction Co. Inc.", "Columbia", "SC"),
    (250, "Pioneer General Contractors Inc.", "Grand Rapids", "MI"),
    (252, "The Bette Cos.", "Latham", "NY"),
    (253, "BBL Construction Services LLC", "Albany", "NY"),
    (254, "Cerris Builders", "Pflugerville", "TX"),
    (255, "Ideal Contracting", "Detroit", "MI"),
    (256, "Haydon Cos.", "Phoenix", "AZ"),
    (257, "Bradbury Stamm Construction Inc.", "Albuquerque", "NM"),
    (258, "Millie and Severson General Contractors", "Los Alamitos", "CA"),
    (259, "Nibbi Bros. Associates Inc.", "San Francisco", "CA"),
    (260, "Shaw Construction", "Denver", "CO"),
    (261, "Shiel Sexton Co. Inc.", "Indianapolis", "IN"),
    (262, "Hausmann Construction", "Lincoln", "NE"),
    (263, "Knutson Construction", "Minneapolis", "MN"),
    (264, "CRB", "Kansas City", "MO"),
    (265, "SEMA Construction Inc.", "Centennial", "CO"),
    (266, "Ruscilli Construction Co. LLC", "Dublin", "OH"),
    (267, "IMC Construction", "Malvern", "PA"),
    (268, "EMJ Construction", "Chattanooga", "TN"),
    (269, "CSI Construction Co.", "Colorado Springs", "CO"),
    (270, "Lydig Construction", "Spokane", "WA"),
    (271, "GH Phipps Construction Co.", "Greenwood Village", "CO"),
    (272, "The Hagerman Group", "Fort Wayne", "IN"),
    (273, "C. Overaa & Co.", "Richmond", "CA"),
    (274, "Sukut Construction LLC", "Santa Ana", "CA"),
    (275, "Kraemer North America LLC", "Plain", "WI"),
    (277, "Russell Group Inc.", "Davenport", "IA"),
    (278, "J. Fletcher Creamer & Son Inc.", "Hackensack", "NJ"),
    (279, "Armada Hoffler", "Virginia Beach", "VA"),
    (280, "Bowen", "Indianapolis", "IN"),
    (281, "T N Ward Co.", "Ardmore", "PA"),
    (282, "Lyles Construction Group", "Fresno", "CA"),
    (283, "Shook Construction", "Moraine", "OH"),
    (284, "Edifice Construction", "Charlotte", "NC"),
    (285, "Schimenti Construction Co.", "New York", "NY"),
    (286, "Parsons Corp.", "Chantilly", "VA"),
    (287, "R&O Construction", "Ogden", "UT"),
    (288, "Charles Perry Partners Inc.", "Gainesville", "FL"),
    (289, "Sevenson Environmental Services Inc.", "Niagara Falls", "NY"),
    (290, "Hill & Wilkinson General Contractors", "Richardson", "TX"),
    (292, "Perlo Construction", "Tualatin", "OR"),
    (293, "Executive Construction Inc.", "Hillside", "IL"),
    (294, "Intech Construction", "Philadelphia", "PA"),
    (295, "Harper General Contractors", "Greenville", "SC"),
    (296, "Kajima Building & Design Group Inc.", "Atlanta", "GA"),
    (297, "Boh Bros. Construction Co. LLC", "New Orleans", "LA"),
    (298, "Capstone Building Corp.", "Birmingham", "AL"),
    (299, "March Associates Construction Inc.", "Wayne", "NJ"),
    (300, "Kiely Family of Cos.", "Tinton Falls", "NJ"),
    (302, "Barr & Barr Inc.", "New York", "NY"),
    (303, "E.W. Howell Co. LLC", "Plainview", "NY"),
    (304, "Haselden Construction", "Centennial", "CO"),
    (305, "Brown Construction Inc.", "West Sacramento", "CA"),
    (306, "LandSouth Construction", "Jacksonville", "FL"),
    (307, "Hawkins Construction Co.", "Omaha", "NE"),
    (308, "Wieland", "Lansing", "MI"),
    (309, "Commodore Builders", "Newton", "MA"),
    (310, "Arch-Con Corp.", "Houston", "TX"),
    (311, "Market & Johnson Inc.", "Eau Claire", "WI"),
    (312, "MEB", "Chesapeake", "VA"),
    (313, "NEI General Contracting", "Randolph", "MA"),
    (314, "Bryan Construction Inc.", "Colorado Springs", "CO"),
    (315, "Callahan Construction Managers", "Bridgewater", "MA"),
    (316, "Parrish Construction Group Inc.", "Perry", "GA"),
    (317, "James E. Roberts - Obayashi Corp.", "Danville", "CA"),
    (318, "Bozzuto Construction", "Greenbelt", "MD"),
    (319, "Gardner Builders", "Minneapolis", "MN"),
    (320, "River City Construction LLC", "East Peoria", "IL"),
    (321, "Deacon Construction LLC", "Portland", "OR"),
    (322, "Buch Construction", "Fulton", "MD"),
    (323, "S. T. Wooten Corp.", "Wilson", "NC"),
    (324, "Fagen Inc.", "Granite Falls", "MN"),
    (326, "Vericon Construction Co.", "Mountainside", "NJ"),
    (327, "Absher Construction Co.", "Puyallup", "WA"),
    (328, "Fort Myer Construction Corp.", "Washington", "DC"),
    (329, "Doster Construction Co. Inc.", "Birmingham", "AL"),
    (330, "BW Design Group", "St. Louis", "MO"),
    (331, "Hourigan", "Richmond", "VA"),
    (332, "William A. Randolph Inc.", "Gurnee", "IL"),
    (333, "Blum Construction", "Winston-Salem", "NC"),
    (334, "Dome Construction Corp.", "South San Francisco", "CA"),
    (335, "Berglund Construction Co.", "Chicago", "IL"),
    (336, "Key Construction Inc.", "Wichita", "KS"),
    (337, "Jaynes Corp.", "Albuquerque", "NM"),
    (338, "JHL Constructors", "Englewood", "CO"),
    (339, "Poettker Construction Co.", "Breese", "IL"),
    (340, "Roebbelen Contracting Inc.", "El Dorado Hills", "CA"),
    (342, "CDM Smith", "Boston", "MA"),
    (343, "Opus", "Minnetonka", "MN"),
    (344, "Holt Construction", "Pearl River", "NY"),
    (347, "Exxel Pacific", "Bellingham", "WA"),
    (348, "Fortune-Johnson LLC", "Peachtree Corners", "GA"),
    (349, "Wagman Inc.", "York", "PA"),
    (350, "Shelco LLC", "Charlotte", "NC"),
    (351, "MCL Construction", "Omaha", "NE"),
    (352, "Triton Construction Co. LLC", "New York", "NY"),
    (353, "Ghilotti Construction Co.", "Santa Rosa", "CA"),
    (354, "KBE Building Corp.", "Farmington", "CT"),
    (355, "PC Construction Co.", "South Burlington", "VT"),
    (356, "Bell & Associates Construction LLC", "Brentwood", "TN"),
    (357, "KBS Inc.", "Richmond", "VA"),
    (358, "Wohlsen Construction Co.", "Lancaster", "PA"),
    (360, "Fontaine Bros. Inc.", "Springfield", "MA"),
    (362, "Kitchell Corp.", "Phoenix", "AZ"),
    (363, "Albert C. Kobayashi Inc.", "Waipahu", "HI"),
    (364, "CF Evans Construction", "Orangeburg", "SC"),
    (365, "Harper Construction Co. Inc.", "San Diego", "CA"),
    (366, "Garco Construction", "Spokane", "WA"),
    (368, "Penntex Construction Co. Inc.", "Blue Bell", "PA"),
    (369, "Ulliman Schutte Construction LLC", "Miamisburg", "OH"),
    (370, "J.D. Eckman Inc.", "Atglen", "PA"),
    (380, "Ridgemont Commercial Co.", "Irving", "TX"),
    (381, "Andres Construction Services", "Dallas", "TX"),
    (384, "Water Resources Group", "Deerwood", "MN"),
    (385, "Donohoe Construction Co.", "Bethesda", "MD"),
    (386, "Blythe Development Co.", "Charlotte", "NC"),
    (389, "WesPac Construction", "Phoenix", "AZ"),
    (390, "Calhoun Construction Services", "Louisville", "KY"),
    (392, "Buffalo Construction", "Louisville", "KY"),
    (393, "Frana Cos. Inc.", "Hopkins", "MN"),
    (394, "Morley Builders", "Santa Monica", "CA"),
    (398, "Galaxy Builders Ltd.", "San Antonio", "TX"),
    (399, "Terminal Construction Corp.", "Wood-Ridge", "NJ"),
]


def get_company_slug(name: str) -> str:
    """Generate a URL-friendly slug from a company name."""
    import re
    slug = name.lower()
    slug = re.sub(r'[^a-z0-9\s-]', '', slug)
    slug = re.sub(r'[\s-]+', '-', slug).strip('-')
    return slug


def get_company_domain_guesses(name: str) -> list[str]:
    """
    Generate likely website domains for a company name.
    Returns a list of URLs to try.
    """
    import re
    # Clean company name for domain guessing
    clean = name.lower()
    # Remove common suffixes
    for suffix in [' inc.', ' inc', ' llc', ' co.', ' co', ' corp.', ' corp',
                   ' cos.', ' cos', ' group', ' holdings', ' holding',
                   ' enterprises', ' services', ' construction',
                   ' contracting', ' builders', ' building',
                   ' general contractors', ' the ', 'the ']:
        clean = clean.replace(suffix, ' ')
    clean = re.sub(r'[^a-z0-9\s]', '', clean).strip()
    parts = clean.split()

    guesses = []
    if len(parts) >= 1:
        # Try various domain patterns
        base = ''.join(parts)
        guesses.append(f"https://www.{base}.com")
        if len(parts) >= 2:
            guesses.append(f"https://www.{parts[0]}{parts[1]}.com")
            guesses.append(f"https://www.{parts[0]}-{parts[1]}.com")
    return guesses[:3]
